name: lgoin_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - images/so.png
  - images/person.png
  - images/buku1.png
  - images/buku2.png
  - images/buku3.png
  - images/buku4.png
  - images/buku5.png
  - images/buku6.png
  - images/buku7.png
  - images/buku8.png
  - images/buku9.png
  - images/buku10.png

    
